version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: reloconnect-postgres
    environment:
      POSTGRES_DB: reloconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reloconnect-network

  # Redis (for sessions and caching)
  redis:
    image: redis:7-alpine
    container_name: reloconnect-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reloconnect-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: reloconnect-auth
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/reloconnect
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-here
      - JWT_REFRESH_SECRET=your-refresh-secret-here
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # Booking Service
  booking-service:
    build:
      context: ./services/booking
      dockerfile: Dockerfile
    container_name: reloconnect-booking
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/reloconnect
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - auth-service
    volumes:
      - ./services/booking:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # Driver Service
  driver-service:
    build:
      context: ./services/driver
      dockerfile: Dockerfile
    container_name: reloconnect-driver
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/reloconnect
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - redis
      - auth-service
    volumes:
      - ./services/driver:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # Realtime Service (Socket.IO)
  realtime-service:
    build:
      context: ./services/realtime
      dockerfile: Dockerfile
    container_name: reloconnect-realtime
    environment:
      - NODE_ENV=development
      - PORT=3004
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
    ports:
      - "3004:3004"
    depends_on:
      - redis
      - auth-service
    volumes:
      - ./services/realtime:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # Payment Service
  payment-service:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    container_name: reloconnect-payment
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/reloconnect
      - STRIPE_SECRET_KEY=sk_test_your_stripe_key
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret
      - AUTH_SERVICE_URL=http://auth-service:3001
    ports:
      - "3005:3005"
    depends_on:
      - postgres
      - auth-service
    volumes:
      - ./services/payment:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # Integration Service
  integration-service:
    build:
      context: ./services/integration
      dockerfile: Dockerfile
    container_name: reloconnect-integration
    environment:
      - NODE_ENV=development
      - PORT=3006
      - NEWS_API_KEY=your_news_api_key
      - GOOGLE_MAPS_API_KEY=your_google_maps_key
      - PORTCAST_API_KEY=your_portcast_key
    ports:
      - "3006:3006"
    volumes:
      - ./services/integration:/app
      - /app/node_modules
    networks:
      - reloconnect-network

  # API Gateway (nginx)
  api-gateway:
    image: nginx:alpine
    container_name: reloconnect-gateway
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - booking-service
      - driver-service
      - realtime-service
      - payment-service
      - integration-service
    networks:
      - reloconnect-network

  # Admin Dashboard
  admin-dashboard:
    build:
      context: ./apps/admin-dashboard
      dockerfile: Dockerfile
    container_name: reloconnect-admin
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3004
    ports:
      - "3010:3010"
    volumes:
      - ./apps/admin-dashboard:/app
      - /app/node_modules
      - /app/.next
    networks:
      - reloconnect-network

volumes:
  postgres_data:
  redis_data:

networks:
  reloconnect-network:
    driver: bridge
